"""
Unit tests for ExternalCallLog ORM model.

Tests:
- Model instantiation with all fields
- Field population and defaults
- Index definitions
- String representation
"""

import uuid
from datetime import datetime, timezone

import pytest

from heretek_swarm.models.external_call_log import ExternalCallLog


class TestExternalCallLogModel:
    """Test suite for ExternalCallLog SQLAlchemy ORM model."""

    def test_model_instantiation_minimal(self) -> None:
        """Test model can be instantiated with minimal required fields."""
        log = ExternalCallLog(
            agent_id="agent-001",
            agent_type="worker",
            call_type="api_call",
            url="https://api.example.com/v1/test",
            method="POST",
        )

        assert log.agent_id == "agent-001"
        assert log.agent_type == "worker"
        assert log.call_type == "api_call"
        assert log.url == "https://api.example.com/v1/test"
        assert log.method == "POST"

    def test_model_instantiation_full(self) -> None:
        """Test model can be instantiated with all fields populated."""
        log_id = uuid.uuid4()
        created = datetime.now(timezone.utc)

        log = ExternalCallLog(
            id=log_id,
            agent_id="agent-002",
            agent_type="orchestrator",
            call_type="http_request",
            url="https://api.example.com/v1/data",
            method="GET",
            status_code=200,
            duration_ms=150.5,
            request_headers_encrypted="encrypted_headers",
            request_body_encrypted="encrypted_body",
            response_body_encrypted="encrypted_response",
            tool_name="fetch_tool",
            error_message=None,
            created_at=created,
        )

        assert log.id == log_id
        assert log.agent_id == "agent-002"
        assert log.agent_type == "orchestrator"
        assert log.call_type == "http_request"
        assert log.url == "https://api.example.com/v1/data"
        assert log.method == "GET"
        assert log.status_code == 200
        assert log.duration_ms == 150.5
        assert log.request_headers_encrypted == "encrypted_headers"
        assert log.request_body_encrypted == "encrypted_body"
        assert log.response_body_encrypted == "encrypted_response"
        assert log.tool_name == "fetch_tool"
        assert log.error_message is None
        assert log.created_at == created

    def test_model_default_values(self) -> None:
        """Test that optional fields default to None."""
        log = ExternalCallLog(
            agent_id="agent-003",
            agent_type="worker",
            call_type="api_call",
            url="https://api.example.com/v1/test",
            method="POST",
        )

        assert log.id is None  # Will be generated by default
        assert log.status_code is None
        assert log.duration_ms is None
        assert log.request_headers_encrypted is None
        assert log.request_body_encrypted is None
        assert log.response_body_encrypted is None
        assert log.tool_name is None
        assert log.error_message is None

    def test_model_id_is_none_until_inserted(self) -> None:
        """Test that id is None on instantiation (set by DB on insert)."""
        log = ExternalCallLog(
            agent_id="agent-004",
            agent_type="worker",
            call_type="api_call",
            url="https://api.example.com/v1/test",
            method="POST",
        )

        # id is None until SQLAlchemy inserts the record
        # The default=uuid.uuid4 is used by the DB, not by Python instantiation
        assert log.id is None

    def test_model_repr(self) -> None:
        """Test model string representation."""
        log = ExternalCallLog(
            agent_id="agent-005",
            agent_type="worker",
            call_type="api_call",
            url="https://api.example.com/v1/test/very/long/path/that/might/be/truncated",
            method="POST",
        )

        repr_str = repr(log)

        assert "ExternalCallLog" in repr_str
        assert "agent_id=agent-005" in repr_str
        assert "call_type=api_call" in repr_str
        # URL should be truncated in repr
        assert "..." in repr_str

    def test_model_field_types(self) -> None:
        """Test that fields have correct types."""
        log = ExternalCallLog(
            agent_id="agent-006",
            agent_type="worker",
            call_type="api_call",
            url="https://api.example.com/v1/test",
            method="POST",
            status_code=201,
            duration_ms=99.9,
        )

        assert isinstance(log.agent_id, str)
        assert isinstance(log.agent_type, str)
        assert isinstance(log.call_type, str)
        assert isinstance(log.url, str)
        assert isinstance(log.method, str)
        assert isinstance(log.status_code, int)
        assert isinstance(log.duration_ms, (int, float))

    def test_model_with_error_message(self) -> None:
        """Test model with error message set."""
        log = ExternalCallLog(
            agent_id="agent-007",
            agent_type="worker",
            call_type="api_call",
            url="https://api.example.com/v1/test",
            method="POST",
            status_code=500,
            error_message="Connection timeout after 30s",
        )

        assert log.status_code == 500
        assert log.error_message == "Connection timeout after 30s"

    def test_model_with_encrypted_data(self) -> None:
        """Test model with encrypted data fields."""
        encrypted_headers = "eyJoZWFkZXIiOiJ2YWx1ZSJ9"  # base64 encoded
        encrypted_body = "eyJib2R5IjoidmFsdWUifQ=="  # base64 encoded

        log = ExternalCallLog(
            agent_id="agent-008",
            agent_type="worker",
            call_type="api_call",
            url="https://api.example.com/v1/test",
            method="POST",
            request_headers_encrypted=encrypted_headers,
            request_body_encrypted=encrypted_body,
            response_body_encrypted=encrypted_body,
        )

        assert log.request_headers_encrypted == encrypted_headers
        assert log.request_body_encrypted == encrypted_body
        assert log.response_body_encrypted == encrypted_body

    def test_model_table_name(self) -> None:
        """Test that model maps to correct table name."""
        assert ExternalCallLog.__tablename__ == "external_call_logs"

    def test_model_has_indexes(self) -> None:
        """Test that model has index definitions."""
        # Check table args exist
        assert hasattr(ExternalCallLog, "__table_args__")

        # Indexes should be defined
        table_args = ExternalCallLog.__table_args__
        assert len(table_args) >= 3  # At least 3 composite indexes

        # Verify index names
        index_names = [idx.name for idx in table_args if hasattr(idx, "name")]
        assert "idx_external_call_logs_agent_created" in index_names
        assert "idx_external_call_logs_call_type_created" in index_names
        assert "idx_external_call_logs_status_code" in index_names

    def test_model_inherits_from_base(self) -> None:
        """Test that model inherits from Base."""
        from heretek_swarm.models.external_call_log import Base

        log = ExternalCallLog(
            agent_id="agent-009",
            agent_type="worker",
            call_type="api_call",
            url="https://api.example.com/v1/test",
            method="GET",
        )

        assert isinstance(log, Base)
