# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import heretek_services_pb2 as heretek__services__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in heretek_services_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConsensusServiceStub:
    """=============================================================================
    Consensus Service (Phase 5.1)
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRound = channel.unary_unary(
                '/heretek.services.v1.ConsensusService/CreateRound',
                request_serializer=heretek__services__pb2.CreateRoundRequest.SerializeToString,
                response_deserializer=heretek__services__pb2.RoundId.FromString,
                _registered_method=True)
        self.AddVote = channel.unary_unary(
                '/heretek.services.v1.ConsensusService/AddVote',
                request_serializer=heretek__services__pb2.AddVoteRequest.SerializeToString,
                response_deserializer=heretek__services__pb2.VoteAck.FromString,
                _registered_method=True)
        self.Compute = channel.unary_unary(
                '/heretek.services.v1.ConsensusService/Compute',
                request_serializer=heretek__services__pb2.ComputeRequest.SerializeToString,
                response_deserializer=heretek__services__pb2.ConsensusResult.FromString,
                _registered_method=True)
        self.StreamRounds = channel.unary_stream(
                '/heretek.services.v1.ConsensusService/StreamRounds',
                request_serializer=heretek__services__pb2.StreamRequest.SerializeToString,
                response_deserializer=heretek__services__pb2.Round.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/heretek.services.v1.ConsensusService/Cancel',
                request_serializer=heretek__services__pb2.CancelRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class ConsensusServiceServicer:
    """=============================================================================
    Consensus Service (Phase 5.1)
    =============================================================================

    """

    def CreateRound(self, request, context):
        """Create a new consensus round.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddVote(self, request, context):
        """Submit a vote to an existing round.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Compute(self, request, context):
        """Compute the final result for a round.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRounds(self, request, context):
        """Server-streaming: live updates as rounds progress.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Cancel an in-flight round.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConsensusServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRound': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRound,
                    request_deserializer=heretek__services__pb2.CreateRoundRequest.FromString,
                    response_serializer=heretek__services__pb2.RoundId.SerializeToString,
            ),
            'AddVote': grpc.unary_unary_rpc_method_handler(
                    servicer.AddVote,
                    request_deserializer=heretek__services__pb2.AddVoteRequest.FromString,
                    response_serializer=heretek__services__pb2.VoteAck.SerializeToString,
            ),
            'Compute': grpc.unary_unary_rpc_method_handler(
                    servicer.Compute,
                    request_deserializer=heretek__services__pb2.ComputeRequest.FromString,
                    response_serializer=heretek__services__pb2.ConsensusResult.SerializeToString,
            ),
            'StreamRounds': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamRounds,
                    request_deserializer=heretek__services__pb2.StreamRequest.FromString,
                    response_serializer=heretek__services__pb2.Round.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=heretek__services__pb2.CancelRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'heretek.services.v1.ConsensusService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('heretek.services.v1.ConsensusService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConsensusService:
    """=============================================================================
    Consensus Service (Phase 5.1)
    =============================================================================

    """

    @staticmethod
    def CreateRound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/heretek.services.v1.ConsensusService/CreateRound',
            heretek__services__pb2.CreateRoundRequest.SerializeToString,
            heretek__services__pb2.RoundId.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/heretek.services.v1.ConsensusService/AddVote',
            heretek__services__pb2.AddVoteRequest.SerializeToString,
            heretek__services__pb2.VoteAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Compute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/heretek.services.v1.ConsensusService/Compute',
            heretek__services__pb2.ComputeRequest.SerializeToString,
            heretek__services__pb2.ConsensusResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamRounds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/heretek.services.v1.ConsensusService/StreamRounds',
            heretek__services__pb2.StreamRequest.SerializeToString,
            heretek__services__pb2.Round.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/heretek.services.v1.ConsensusService/Cancel',
            heretek__services__pb2.CancelRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MemoryServiceStub:
    """=============================================================================
    Memory Service (Phase 5.2)
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Add = channel.unary_unary(
                '/heretek.services.v1.MemoryService/Add',
                request_serializer=heretek__services__pb2.AddMemoryRequest.SerializeToString,
                response_deserializer=heretek__services__pb2.AddMemoryAck.FromString,
                _registered_method=True)
        self.Read = channel.unary_unary(
                '/heretek.services.v1.MemoryService/Read',
                request_serializer=heretek__services__pb2.ReadMemoryRequest.SerializeToString,
                response_deserializer=heretek__services__pb2.MemoryEntry.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/heretek.services.v1.MemoryService/Search',
                request_serializer=heretek__services__pb2.SearchMemoryRequest.SerializeToString,
                response_deserializer=heretek__services__pb2.SearchMemoryResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/heretek.services.v1.MemoryService/Health',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=heretek__services__pb2.HealthResponse.FromString,
                _registered_method=True)


class MemoryServiceServicer:
    """=============================================================================
    Memory Service (Phase 5.2)
    =============================================================================

    """

    def Add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=heretek__services__pb2.AddMemoryRequest.FromString,
                    response_serializer=heretek__services__pb2.AddMemoryAck.SerializeToString,
            ),
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=heretek__services__pb2.ReadMemoryRequest.FromString,
                    response_serializer=heretek__services__pb2.MemoryEntry.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=heretek__services__pb2.SearchMemoryRequest.FromString,
                    response_serializer=heretek__services__pb2.SearchMemoryResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=heretek__services__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'heretek.services.v1.MemoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('heretek.services.v1.MemoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryService:
    """=============================================================================
    Memory Service (Phase 5.2)
    =============================================================================

    """

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/heretek.services.v1.MemoryService/Add',
            heretek__services__pb2.AddMemoryRequest.SerializeToString,
            heretek__services__pb2.AddMemoryAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/heretek.services.v1.MemoryService/Read',
            heretek__services__pb2.ReadMemoryRequest.SerializeToString,
            heretek__services__pb2.MemoryEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/heretek.services.v1.MemoryService/Search',
            heretek__services__pb2.SearchMemoryRequest.SerializeToString,
            heretek__services__pb2.SearchMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/heretek.services.v1.MemoryService/Health',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            heretek__services__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RealtimeServiceStub:
    """=============================================================================
    Realtime Service (Phase 5.3)
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BroadcastDashboard = channel.unary_unary(
                '/heretek.services.v1.RealtimeService/BroadcastDashboard',
                request_serializer=heretek__services__pb2.BroadcastRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.BroadcastA2A = channel.unary_unary(
                '/heretek.services.v1.RealtimeService/BroadcastA2A',
                request_serializer=heretek__services__pb2.BroadcastRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.BroadcastExternalCall = channel.unary_unary(
                '/heretek.services.v1.RealtimeService/BroadcastExternalCall',
                request_serializer=heretek__services__pb2.BroadcastRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.BroadcastAgentUpdate = channel.unary_unary(
                '/heretek.services.v1.RealtimeService/BroadcastAgentUpdate',
                request_serializer=heretek__services__pb2.BroadcastRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class RealtimeServiceServicer:
    """=============================================================================
    Realtime Service (Phase 5.3)
    =============================================================================

    """

    def BroadcastDashboard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BroadcastA2A(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BroadcastExternalCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BroadcastAgentUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RealtimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BroadcastDashboard': grpc.unary_unary_rpc_method_handler(
                    servicer.BroadcastDashboard,
                    request_deserializer=heretek__services__pb2.BroadcastRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'BroadcastA2A': grpc.unary_unary_rpc_method_handler(
                    servicer.BroadcastA2A,
                    request_deserializer=heretek__services__pb2.BroadcastRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'BroadcastExternalCall': grpc.unary_unary_rpc_method_handler(
                    servicer.BroadcastExternalCall,
                    request_deserializer=heretek__services__pb2.BroadcastRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'BroadcastAgentUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.BroadcastAgentUpdate,
                    request_deserializer=heretek__services__pb2.BroadcastRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'heretek.services.v1.RealtimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('heretek.services.v1.RealtimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RealtimeService:
    """=============================================================================
    Realtime Service (Phase 5.3)
    =============================================================================

    """

    @staticmethod
    def BroadcastDashboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/heretek.services.v1.RealtimeService/BroadcastDashboard',
            heretek__services__pb2.BroadcastRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BroadcastA2A(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/heretek.services.v1.RealtimeService/BroadcastA2A',
            heretek__services__pb2.BroadcastRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BroadcastExternalCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/heretek.services.v1.RealtimeService/BroadcastExternalCall',
            heretek__services__pb2.BroadcastRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BroadcastAgentUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/heretek.services.v1.RealtimeService/BroadcastAgentUpdate',
            heretek__services__pb2.BroadcastRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ObservabilityServiceStub:
    """=============================================================================
    Observability Service (Phase 5.4)
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EmitSpan = channel.unary_unary(
                '/heretek.services.v1.ObservabilityService/EmitSpan',
                request_serializer=heretek__services__pb2.SpanRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.TrackMetric = channel.unary_unary(
                '/heretek.services.v1.ObservabilityService/TrackMetric',
                request_serializer=heretek__services__pb2.MetricRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.FireAlert = channel.unary_unary(
                '/heretek.services.v1.ObservabilityService/FireAlert',
                request_serializer=heretek__services__pb2.AlertRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/heretek.services.v1.ObservabilityService/Health',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=heretek__services__pb2.HealthResponse.FromString,
                _registered_method=True)


class ObservabilityServiceServicer:
    """=============================================================================
    Observability Service (Phase 5.4)
    =============================================================================

    """

    def EmitSpan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrackMetric(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FireAlert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObservabilityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EmitSpan': grpc.unary_unary_rpc_method_handler(
                    servicer.EmitSpan,
                    request_deserializer=heretek__services__pb2.SpanRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'TrackMetric': grpc.unary_unary_rpc_method_handler(
                    servicer.TrackMetric,
                    request_deserializer=heretek__services__pb2.MetricRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'FireAlert': grpc.unary_unary_rpc_method_handler(
                    servicer.FireAlert,
                    request_deserializer=heretek__services__pb2.AlertRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=heretek__services__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'heretek.services.v1.ObservabilityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('heretek.services.v1.ObservabilityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ObservabilityService:
    """=============================================================================
    Observability Service (Phase 5.4)
    =============================================================================

    """

    @staticmethod
    def EmitSpan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/heretek.services.v1.ObservabilityService/EmitSpan',
            heretek__services__pb2.SpanRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrackMetric(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/heretek.services.v1.ObservabilityService/TrackMetric',
            heretek__services__pb2.MetricRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FireAlert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/heretek.services.v1.ObservabilityService/FireAlert',
            heretek__services__pb2.AlertRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/heretek.services.v1.ObservabilityService/Health',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            heretek__services__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
