"""
Goal data model for the heretek-swarm autonomous goal system.

Goals are strategic proposals generated by Metis (the strategic planning agent)
that flow through MAKER consensus voting before being accepted or rejected.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import UTC, datetime
from typing import Any, Literal

GoalStatus = Literal[
    "proposed", "voting", "accepted", "rejected", "error", "executing", "completed"
]


@dataclass
class Vote:
    """A single agent vote on a goal proposal.

    Attributes:
        agent_id: The voting agent's identifier.
        decision: The vote choice — ``"approve"``, ``"reject"``, or ``"abstain"``.
        confidence: Agent's confidence in their vote (0.0 – 1.0).
        rationale: Brief reason for the vote (optional).
        timestamp: ISO-8601 timestamp of when the vote was cast.
    """

    agent_id: str
    decision: Literal["approve", "reject", "abstain"]
    confidence: float
    rationale: str = ""
    timestamp: str = ""

    def __post_init__(self) -> None:
        if not self.timestamp:
            self.timestamp = datetime.now(UTC).isoformat()


@dataclass
class Goal:
    """A strategic goal proposed by the swarm.

    Goals move through a lifecycle:
    ``proposed`` → ``voting`` → ``accepted`` / ``rejected`` → ``executing`` → ``completed`` / ``error``.

    Attributes:
        id: Unique goal identifier (generated at proposal time).
        title: Short, human-readable goal title.
        description: Full goal description with motivation and scope.
        success_criteria: Measurable criteria that define goal completion.
        status: Current lifecycle state.
        votes: List of agent votes cast during the voting phase.
        estimated_node_types: Optional hints about expected workflow nodes.
        execution_results: Optional results from goal execution (populated post-acceptance).
        created_at: ISO-8601 timestamp of proposal creation.
        updated_at: ISO-8601 timestamp of last state change.
    """

    id: str
    title: str
    description: str
    success_criteria: list[str] = field(default_factory=list)
    status: GoalStatus = "proposed"
    votes: list[dict[str, Any]] = field(default_factory=list)
    estimated_node_types: list[str] = field(default_factory=list)
    execution_results: dict[str, Any] | None = None
    created_at: str = ""
    updated_at: str = ""

    def __post_init__(self) -> None:
        now = datetime.now(UTC).isoformat()
        if not self.created_at:
            self.created_at = now
        if not self.updated_at:
            self.updated_at = now

    def to_dict(self) -> dict[str, Any]:
        """Serialize the goal to a plain dict for JSON storage."""
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Goal:
        """Deserialize a Goal from a plain dict.

        Handles both the current schema and gracefully degrades for
        missing optional fields.
        """
        return cls(
            id=data["id"],
            title=data["title"],
            description=data["description"],
            success_criteria=data.get("success_criteria", []),
            status=data.get("status", "proposed"),
            votes=data.get("votes", []),
            estimated_node_types=data.get("estimated_node_types", []),
            execution_results=data.get("execution_results"),
            created_at=data.get("created_at", ""),
            updated_at=data.get("updated_at", ""),
        )

    def add_vote(self, vote: Vote) -> None:
        """Record a vote and bump the updated_at timestamp.

        The status change to/accepted/rejected/voting is handled
        by the store layer so that atomicity around consensus is
        preserved."""
        self.votes.append(asdict(vote))
        self.updated_at = datetime.now(UTC).isoformat()
