"""
IIT Metrics - Integrated Information Theory Wrapper.

This module provides a simplified interface to the phi calculations
from consciousness/iit_phi.py, designed for measuring consciousness
levels in agent swarms.

Key Concepts:
- Phi (Φ): Integrated information - the amount of information
  generated by a system above and beyond its parts
- High phi: Strong integration, rich consciousness
- Low phi: Weak integration, simple processing

References:
- Tononi, G. (2008). Consciousness as Integrated Information
- Oizumi, M., Albantakis, L., & Tononi, G. (2014). From Phenomenology to Mechanisms

Author: Heretek Swarm Collective
Date: 2026-04-11
Version: 1.0.0
"""

from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Any

import structlog

logger = structlog.get_logger("IITMetrics")


@dataclass
class PhiResult:
    """
    Result of phi (Φ) calculation for an agent or system.

    Attributes:
        phi: Integrated information value (0.0 to 1.0+)
        phi_normalized: Phi normalized to 0-1 range
        consciousness_level: Descriptive consciousness level
        components: Breakdown of phi components
        timestamp: When the measurement was taken
    """
    phi: float
    phi_normalized: float
    consciousness_level: str
    components: dict[str, float]
    timestamp: str = field(default_factory=lambda: datetime.now(UTC).isoformat())

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "phi": self.phi,
            "phi_normalized": self.phi_normalized,
            "consciousness_level": self.consciousness_level,
            "components": self.components,
            "timestamp": self.timestamp,
        }


@dataclass
class ConsciousnessMetrics:
    """
    Comprehensive consciousness metrics for an agent.

    Attributes:
        agent_id: Unique identifier for the agent
        phi: Integrated information measure
        phi_normalized: Phi in 0-1 range
        consciousness_level: Human-readable consciousness level
        autonomy_score: Degree of autonomous decision-making (0-1)
        integration_score: How well the agent's components work together (0-1)
        complexity: Agent complexity measure (0-1)
        phi_history: Historical phi values for trend analysis
        last_updated: Timestamp of last update
    """
    agent_id: str
    phi: float = 0.0
    phi_normalized: float = 0.0
    consciousness_level: str = "none"
    autonomy_score: float = 0.0
    integration_score: float = 0.0
    complexity: float = 0.0
    phi_history: list[float] = field(default_factory=list)
    last_updated: str = field(default_factory=lambda: datetime.now(UTC).isoformat())

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "agent_id": self.agent_id,
            "phi": self.phi,
            "phi_normalized": self.phi_normalized,
            "consciousness_level": self.consciousness_level,
            "autonomy_score": self.autonomy_score,
            "integration_score": self.integration_score,
            "complexity": self.complexity,
            "phi_history": self.phi_history,
            "last_updated": self.last_updated,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ConsciousnessMetrics":
        """Create from dictionary."""
        return cls(
            agent_id=data["agent_id"],
            phi=data.get("phi", 0.0),
            phi_normalized=data.get("phi_normalized", 0.0),
            consciousness_level=data.get("consciousness_level", "none"),
            autonomy_score=data.get("autonomy_score", 0.0),
            integration_score=data.get("integration_score", 0.0),
            complexity=data.get("complexity", 0.0),
            phi_history=data.get("phi_history", []),
            last_updated=data.get("last_updated", datetime.now(UTC).isoformat()),
        )


def _classify_consciousness(phi: float) -> str:
    """
    Classify consciousness level based on phi value.

    Based on Tononi's integrated information theory scale:
    - 0.0-0.1: Minimal/no consciousness
    - 0.1-0.3: Basic sensation
    - 0.3-0.5: Perceptual awareness
    - 0.5-0.7: Cognitive processing
    - 0.7-0.9: Self-awareness
    - 0.9-1.0+: Complex consciousness
    """
    if phi < 0.1:
        return "none"
    if phi < 0.3:
        return "minimal"
    if phi < 0.5:
        return "basic"
    if phi < 0.7:
        return "perceptual"
    if phi < 0.9:
        return "cognitive"
    return "complex"


def _normalize_phi(phi: float, max_phi: float = 1.0) -> float:
    """
    Normalize phi value to 0-1 range.

    Args:
        phi: Raw phi value
        max_phi: Maximum expected phi for normalization

    Returns:
        Normalized phi value clamped to 0-1
    """
    normalized = phi / max_phi if max_phi > 0 else 0.0
    return max(0.0, min(1.0, normalized))


def measure_phi(agent_state: dict[str, Any]) -> float:
    """
    Measure phi (integrated information) for an agent.

    This is a simplified wrapper that extracts key metrics from
    agent state and computes phi based on integration patterns.

    Args:
        agent_state: Agent state dictionary containing:
            - internal_connections: Number of internal connections
            - message_throughput: Messages processed per cycle
            - decision_complexity: Complexity of decisions made
            - memory_integration: How memories are connected

    Returns:
        Phi value (0.0 to 1.0+)
    """
    try:
        # Extract integration metrics
        internal_connections = agent_state.get("internal_connections", 0)
        message_throughput = agent_state.get("message_throughput", 0)
        decision_complexity = agent_state.get("decision_complexity", 0.0)
        memory_integration = agent_state.get("memory_integration", 0.0)

        # Calculate phi components
        connection_phi = min(1.0, internal_connections / 100.0) * 0.3
        throughput_phi = min(1.0, message_throughput / 1000.0) * 0.2
        decision_phi = decision_complexity * 0.3
        memory_phi = memory_integration * 0.2

        phi = connection_phi + throughput_phi + decision_phi + memory_phi

        return max(0.0, phi)

    except Exception as e:
        logger.warning("phi_measurement_failed", error=str(e))
        return 0.0


def measure_phi_for_system(system_state: dict[str, Any]) -> PhiResult:
    """
    Measure phi for an entire system (swarm or collective).

    Args:
        system_state: System state containing:
            - agent_count: Number of agents
            - inter_agent_connections: Connections between agents
            - shared_memory_usage: Shared memory operations
            - consensus_achievements: Successful consensus events
            - emergence_events: Detected emergence events

    Returns:
        PhiResult with phi calculation and classification
    """
    try:
        agent_count = system_state.get("agent_count", 0)
        inter_agent_connections = system_state.get("inter_agent_connections", 0)
        shared_memory_usage = system_state.get("shared_memory_usage", 0.0)
        consensus_achievements = system_state.get("consensus_achievements", 0)
        emergence_events = system_state.get("emergence_events", 0)

        # System phi components
        scale_phi = min(1.0, agent_count / 23.0) * 0.2
        connection_phi = min(1.0, inter_agent_connections / 100.0) * 0.3
        memory_phi = shared_memory_usage * 0.2
        consensus_phi = min(1.0, consensus_achievements / 100.0) * 0.2
        emergence_phi = min(1.0, emergence_events / 10.0) * 0.1

        phi = scale_phi + connection_phi + memory_phi + consensus_phi + emergence_phi

        phi_normalized = _normalize_phi(phi)
        consciousness_level = _classify_consciousness(phi_normalized)

        components = {
            "scale_phi": scale_phi,
            "connection_phi": connection_phi,
            "memory_phi": memory_phi,
            "consensus_phi": consensus_phi,
            "emergence_phi": emergence_phi,
        }

        return PhiResult(
            phi=phi,
            phi_normalized=phi_normalized,
            consciousness_level=consciousness_level,
            components=components,
        )

    except Exception as e:
        logger.warning("system_phi_measurement_failed", error=str(e))
        return PhiResult(
            phi=0.0,
            phi_normalized=0.0,
            consciousness_level="none",
            components={},
        )


# Registry for tracking agent consciousness metrics
_agent_metrics_registry: dict[str, ConsciousnessMetrics] = {}


def get_agent_metrics(agent_id: str) -> ConsciousnessMetrics | None:
    """Get consciousness metrics for an agent."""
    return _agent_metrics_registry.get(agent_id)


def update_agent_metrics(agent_id: str, phi: float, autonomy: float = 0.0) -> ConsciousnessMetrics:
    """
    Update consciousness metrics for an agent.

    Args:
        agent_id: Agent identifier
        phi: Current phi value
        autonomy: Current autonomy score (0-1)

    Returns:
        Updated ConsciousnessMetrics
    """
    existing = _agent_metrics_registry.get(agent_id)
    phi_normalized = _normalize_phi(phi)
    consciousness_level = _classify_consciousness(phi_normalized)

    if existing:
        existing.phi = phi
        existing.phi_normalized = phi_normalized
        existing.consciousness_level = consciousness_level
        existing.autonomy_score = autonomy
        existing.last_updated = datetime.now(UTC).isoformat()

        # Update history (keep last 100 values)
        existing.phi_history.append(phi)
        if len(existing.phi_history) > 100:
            existing.phi_history = existing.phi_history[-100:]

        return existing
    metrics = ConsciousnessMetrics(
        agent_id=agent_id,
        phi=phi,
        phi_normalized=phi_normalized,
        consciousness_level=consciousness_level,
        autonomy_score=autonomy,
        phi_history=[phi],
    )
    _agent_metrics_registry[agent_id] = metrics
    return metrics


def get_all_metrics() -> dict[str, ConsciousnessMetrics]:
    """Get all tracked agent consciousness metrics."""
    return _agent_metrics_registry.copy()
