"""
IIT Metrics - Integrated Information Theory Implementation.

This module implements Integrated Information Theory (IIT) for measuring
consciousness levels in agent swarms. IIT proposes that consciousness
corresponds to the amount of integrated information (phi) generated by a system.

Key Concepts:
- Phi (Φ): Integrated information - amount of information generated by a system
- Cause-Effect Structure: Causal architecture of the system
- System Integration: How well system components work together
- Consciousness Level: Classification based on phi value

References:
- Tononi, G. (2004). Consciousness and the Brain
- Oizumi, M., Albantakis, L., & Tononi, G. (2014). From Phenomenology to Mechanisms

Author: Heretek Swarm Collective
Date: 2026-04-15
Version: 1.0.0
"""

from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import Enum
from typing import Any
import math

import structlog

logger = structlog.get_logger("IITMetrics")


class ConsciousnessLevel(Enum):
    """Consciousness level classification based on phi."""

    NONE = "none"
    MINIMAL = "minimal"
    BASIC = "basic"
    PERCEPTUAL = "perceptual"
    COGNITIVE = "cognitive"
    COMPLEX = "complex"


@dataclass
class CauseEffectStructure:
    """
    Cause-effect structure tracking for IIT.

    Tracks the causal relationships within a system:
    - Cause repertoire: Possible causes of current state
    - Effect repertoire: Possible effects of current state
    - Information: Information generated by cause-effect structure

    Attributes:
        system_id: Identifier for the system
        cause_repertoire_size: Number of possible causes
        effect_repertoire_size: Number of possible effects
        information_generated: Information generated by cause-effect
        mechanism_count: Number of causal mechanisms
        timestamp: Measurement timestamp
    """

    system_id: str
    cause_repertoire_size: int = 0
    effect_repertoire_size: int = 0
    information_generated: float = 0.0
    mechanism_count: int = 0
    timestamp: str = field(default_factory=lambda: datetime.now(UTC).isoformat())

    def to_dict(self) -> dict[str, Any]:
        return {
            "system_id": self.system_id,
            "cause_repertoire_size": self.cause_repertoire_size,
            "effect_repertoire_size": self.effect_repertoire_size,
            "information_generated": self.information_generated,
            "mechanism_count": self.mechanism_count,
            "timestamp": self.timestamp,
        }


@dataclass
class IntegrationMetrics:
    """
    System integration level measurement.

    Attributes:
        system_id: System identifier
        internal_integration: Integration within the system
        external_integration: Integration with external environment
        partition_looseness: How loosely the system can be partitioned
        integration_score: Overall integration score (0-1)
        timestamp: Measurement timestamp
    """

    system_id: str
    internal_integration: float = 0.0
    external_integration: float = 0.0
    partition_looseness: float = 0.0
    integration_score: float = 0.0
    timestamp: str = field(default_factory=lambda: datetime.now(UTC).isoformat())

    def to_dict(self) -> dict[str, Any]:
        return {
            "system_id": self.system_id,
            "internal_integration": self.internal_integration,
            "external_integration": self.external_integration,
            "partition_looseness": self.partition_looseness,
            "integration_score": self.integration_score,
            "timestamp": self.timestamp,
        }


@dataclass
class PhiResult:
    """
    Result of phi (Φ) calculation for an agent or system.

    Attributes:
        system_id: Unique identifier for the system
        phi: Raw integrated information value
        phi_normalized: Phi normalized to 0-1 range
        consciousness_level: Classification of consciousness level
        cause_effect: Cause-effect structure metrics
        integration: Integration metrics
        components: Breakdown of phi components
        timestamp: Measurement timestamp
    """

    system_id: str
    phi: float = 0.0
    phi_normalized: float = 0.0
    consciousness_level: ConsciousnessLevel = ConsciousnessLevel.NONE
    cause_effect: CauseEffectStructure | None = None
    integration: IntegrationMetrics | None = None
    components: dict[str, float] = field(default_factory=dict)
    timestamp: str = field(default_factory=lambda: datetime.now(UTC).isoformat())

    def to_dict(self) -> dict[str, Any]:
        return {
            "system_id": self.system_id,
            "phi": self.phi,
            "phi_normalized": self.phi_normalized,
            "consciousness_level": self.consciousness_level.value,
            "cause_effect": self.cause_effect.to_dict() if self.cause_effect else None,
            "integration": self.integration.to_dict() if self.integration else None,
            "components": self.components,
            "timestamp": self.timestamp,
        }


def calculate_phi(agent_state: dict[str, Any]) -> float:
    """
    Calculate phi (integrated information) for an agent.

    Args:
        agent_state: Agent state containing:
            - internal_connections: Number of internal connections
            - message_throughput: Messages processed per cycle
            - decision_complexity: Complexity of decisions made
            - memory_integration: How memories are connected

    Returns:
        Phi value (0.0 to 1.0+)
    """
    internal_connections = agent_state.get("internal_connections", 0)
    message_throughput = agent_state.get("message_throughput", 0)
    decision_complexity = agent_state.get("decision_complexity", 0.0)
    memory_integration = agent_state.get("memory_integration", 0.0)

    connection_phi = min(1.0, internal_connections / 100.0) * 0.3
    throughput_phi = min(1.0, message_throughput / 1000.0) * 0.2
    decision_phi = decision_complexity * 0.3
    memory_phi = memory_integration * 0.2

    phi = connection_phi + throughput_phi + decision_phi + memory_phi
    return max(0.0, phi)


def calculate_phi_for_system(system_state: dict[str, Any]) -> PhiResult:
    """
    Calculate phi for an entire system (swarm or collective).

    Args:
        system_state: System state containing:
            - agent_count: Number of agents
            - inter_agent_connections: Connections between agents
            - shared_memory_usage: Shared memory operations
            - consensus_achievements: Successful consensus events
            - emergence_events: Detected emergence events

    Returns:
        PhiResult with phi calculation and classification
    """
    system_id = system_state.get("system_id", "unknown")
    agent_count = system_state.get("agent_count", 0)
    inter_agent_connections = system_state.get("inter_agent_connections", 0)
    shared_memory_usage = system_state.get("shared_memory_usage", 0.0)
    consensus_achievements = system_state.get("consensus_achievements", 0)
    emergence_events = system_state.get("emergence_events", 0)

    scale_phi = min(1.0, agent_count / 23.0) * 0.2
    connection_phi = min(1.0, inter_agent_connections / 100.0) * 0.3
    memory_phi = shared_memory_usage * 0.2
    consensus_phi = min(1.0, consensus_achievements / 100.0) * 0.2
    emergence_phi = min(1.0, emergence_events / 10.0) * 0.1

    phi = scale_phi + connection_phi + memory_phi + consensus_phi + emergence_phi

    phi_normalized = min(1.0, phi)

    consciousness_level = ConsciousnessLevel.NONE
    if phi_normalized >= 0.9:
        consciousness_level = ConsciousnessLevel.COMPLEX
    elif phi_normalized >= 0.7:
        consciousness_level = ConsciousnessLevel.COGNITIVE
    elif phi_normalized >= 0.5:
        consciousness_level = ConsciousnessLevel.PERCEPTUAL
    elif phi_normalized >= 0.3:
        consciousness_level = ConsciousnessLevel.BASIC
    elif phi_normalized >= 0.1:
        consciousness_level = ConsciousnessLevel.MINIMAL

    cause_effect = CauseEffectStructure(
        system_id=system_id,
        cause_repertoire_size=agent_count,
        effect_repertoire_size=inter_agent_connections,
        information_generated=phi * 10.0,
        mechanism_count=inter_agent_connections,
    )

    integration = IntegrationMetrics(
        system_id=system_id,
        internal_integration=connection_phi,
        external_integration=scale_phi,
        partition_looseness=1.0 - consensus_phi,
        integration_score=phi_normalized,
    )

    components = {
        "scale_phi": scale_phi,
        "connection_phi": connection_phi,
        "memory_phi": memory_phi,
        "consensus_phi": consensus_phi,
        "emergence_phi": emergence_phi,
    }

    return PhiResult(
        system_id=system_id,
        phi=phi,
        phi_normalized=phi_normalized,
        consciousness_level=consciousness_level,
        cause_effect=cause_effect,
        integration=integration,
        components=components,
    )


def calculate_cause_effect_structure(
    system_id: str,
    connections: list[tuple[str, str]],
    states: list[dict[str, Any]],
) -> CauseEffectStructure:
    """
    Calculate cause-effect structure for a system.

    Args:
        system_id: System identifier
        connections: List of causal connections (source, target)
        states: List of system states

    Returns:
        CauseEffectStructure for the system
    """
    mechanism_count = len(connections)

    cause_repertoire_size = len(set(c[0] for c in connections)) if connections else 0
    effect_repertoire_size = len(set(c[1] for c in connections)) if connections else 0

    state_diversity = len(set(str(s) for s in states)) if states else 0
    information_generated = math.log2(max(1, state_diversity)) / 10.0

    return CauseEffectStructure(
        system_id=system_id,
        cause_repertoire_size=cause_repertoire_size,
        effect_repertoire_size=effect_repertoire_size,
        information_generated=min(1.0, information_generated),
        mechanism_count=mechanism_count,
    )


def calculate_integration_metrics(
    system_id: str,
    internal_connections: int,
    external_connections: int,
    partition_count: int,
    total_possible_partitions: int,
) -> IntegrationMetrics:
    """
    Calculate system integration level.

    Args:
        system_id: System identifier
        internal_connections: Internal connections within system
        external_connections: Connections to external systems
        partition_count: Number of partitions the system can be broken into
        total_possible_partitions: Total possible partition configurations

    Returns:
        IntegrationMetrics for the system
    """
    max_internal = 100
    max_external = 50

    internal_integration = min(1.0, internal_connections / max_internal)

    external_integration = min(1.0, external_connections / max_external)

    partition_looseness = 1.0 - (partition_count / max(1, total_possible_partitions))

    integration_score = (
        internal_integration * 0.5 + external_integration * 0.2 + partition_looseness * 0.3
    )

    return IntegrationMetrics(
        system_id=system_id,
        internal_integration=internal_integration,
        external_integration=external_integration,
        partition_looseness=partition_looseness,
        integration_score=min(1.0, integration_score),
    )


def calculate_integrated_information(
    system_id: str,
    system_state: dict[str, Any],
) -> PhiResult:
    """
    Calculate integrated information for a system.

    This combines phi, cause-effect structure, and integration metrics
    into a comprehensive IIT measurement.

    Args:
        system_id: System identifier
        system_state: Full system state

    Returns:
        PhiResult with comprehensive IIT metrics
    """
    agent_count = system_state.get("agent_count", 0)
    inter_agent_connections = system_state.get("inter_agent_connections", 0)

    connections = system_state.get("connections", [])
    states = system_state.get("states", [])

    cause_effect = calculate_cause_effect_structure(system_id, connections, states)

    integration = calculate_integration_metrics(
        system_id,
        inter_agent_connections,
        system_state.get("external_connections", 0),
        system_state.get("partition_count", 1),
        system_state.get("total_partitions", 10),
    )

    base_phi = calculate_phi(system_state)
    phi_adjustment = cause_effect.information_generated * 0.2 + integration.integration_score * 0.3

    phi = base_phi * (1.0 + phi_adjustment)
    phi_normalized = min(1.0, phi)

    consciousness_level = ConsciousnessLevel.NONE
    if phi_normalized >= 0.9:
        consciousness_level = ConsciousnessLevel.COMPLEX
    elif phi_normalized >= 0.7:
        consciousness_level = ConsciousnessLevel.COGNITIVE
    elif phi_normalized >= 0.5:
        consciousness_level = ConsciousnessLevel.PERCEPTUAL
    elif phi_normalized >= 0.3:
        consciousness_level = ConsciousnessLevel.BASIC
    elif phi_normalized >= 0.1:
        consciousness_level = ConsciousnessLevel.MINIMAL

    components = {
        "base_phi": base_phi,
        "cause_effect_contribution": phi_adjustment * 0.2,
        "integration_contribution": phi_adjustment * 0.3,
    }

    return PhiResult(
        system_id=system_id,
        phi=phi,
        phi_normalized=phi_normalized,
        consciousness_level=consciousness_level,
        cause_effect=cause_effect,
        integration=integration,
        components=components,
    )


_agent_metrics: dict[str, PhiResult] = {}


def update_agent_phi(agent_id: str, phi_result: PhiResult) -> None:
    """Update phi metrics for an agent."""
    _agent_metrics[agent_id] = phi_result


def get_agent_phi(agent_id: str) -> PhiResult | None:
    """Get phi metrics for an agent."""
    return _agent_metrics.get(agent_id)


def get_all_phi_metrics() -> dict[str, PhiResult]:
    """Get all tracked phi metrics."""
    return _agent_metrics.copy()


class IITTracker:
    """
    Tracker for IIT metrics with history and analysis.

    Provides methods for tracking phi over time and analyzing
    consciousness level changes.
    """

    def __init__(self, history_limit: int = 100):
        self._history: dict[str, list[PhiResult]] = {}
        self._history_limit = history_limit

    def track(self, system_id: str, system_state: dict[str, Any]) -> PhiResult:
        """
        Track phi for a system.

        Args:
            system_id: System identifier
            system_state: Current system state

        Returns:
            PhiResult for the system
        """
        result = calculate_integrated_information(system_id, system_state)

        if system_id not in self._history:
            self._history[system_id] = []
        self._history[system_id].append(result)

        if len(self._history[system_id]) > self._history_limit:
            self._history[system_id] = self._history[system_id][-self._history_limit :]

        update_agent_phi(system_id, result)

        return result

    def get_history(self, system_id: str) -> list[PhiResult]:
        """Get phi history for a system."""
        return self._history.get(system_id, [])

    def get_phi_trend(self, system_id: str) -> list[float]:
        """Get phi values over time."""
        return [r.phi_normalized for r in self._history.get(system_id, [])]

    def get_consciousness_trend(self, system_id: str) -> list[ConsciousnessLevel]:
        """Get consciousness level changes over time."""
        return [r.consciousness_level for r in self._history.get(system_id, [])]

    def get_statistics(self, system_id: str) -> dict[str, Any]:
        """Get statistics for a system's phi history."""
        history = self._history.get(system_id, [])
        if not history:
            return {}

        phi_values = [r.phi_normalized for r in history]

        return {
            "phi_mean": sum(phi_values) / len(phi_values),
            "phi_min": min(phi_values),
            "phi_max": max(phi_values),
            "phi_current": phi_values[-1],
            "consciousness_current": history[-1].consciousness_level.value,
            "samples": len(history),
        }
